version: "3"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - /client/node_modules
      - ./client:/client
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    volumes:
      - ./server:/server
      - /server/node_modules
    environment:
      - MONGO_USER=alenakatkova
      - MONGO_PASSWORD=mypassword
    command: yarn run dev

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alenakatkova
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - db:/data/db

volumes:
  db: