version: "3"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    volumes:
      - ./server:/server
      - /server/node_modules
    environment:
      - MONGO_USER=alenakatkova
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
    command: yarn run dev

  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alenakatkova
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
      - MONGO_INITDB_DATABASE=test
    volumes:
      - ./mongo-seed:/docker-entrypoint-initdb.d
      - db:/data/mongo-seed

  redis:
    image: redis

volumes:
  db:
