print(
  "Start #################################################################"
);

const languagesIds = {
  arabic: ObjectId(),
  chinese: ObjectId(),
  czech: ObjectId(),
  dutch: ObjectId(),
  english: ObjectId(),
  french: ObjectId(),
  german: ObjectId(),
  hebrew: ObjectId(),
  italian: ObjectId(),
  japanese: ObjectId(),
  korean: ObjectId(),
  polish: ObjectId(),
  portuguese: ObjectId(),
  russian: ObjectId(),
  spanish: ObjectId(),
  swedish: ObjectId(),
};

const testsIds = {
  alpt: ObjectId(),
  hsk: ObjectId(),
  tocfl: ObjectId(),
  ilce: ObjectId(),
  ecl: ObjectId(),
  cce: ObjectId(),
  staatsexamen_nt2: ObjectId(),
  cnavt: ObjectId(),
  cal: ObjectId(),
  ielts: ObjectId(),
  toefl: ObjectId(),
  delf: ObjectId(),
  dalf: ObjectId(),
  goethe: ObjectId(),
  testdaf: ObjectId(),
  telc: ObjectId(),
  yael: ObjectId(),
  cils: ObjectId(),
  celi: ObjectId(),
  jlpt: ObjectId(),
  topik: ObjectId(),
  klat: ObjectId(),
  caple: ObjectId(),
  dele: ObjectId(),
  tisus: ObjectId(),
  swedex: ObjectId(),
  torfl: ObjectId(),
};

const levelsIds = {
  a1: ObjectId(),
  a2: ObjectId(),
  b1: ObjectId(),
  b2: ObjectId(),
  c1: ObjectId(),
  c2: ObjectId(),
};

db.tests.insertMany([
  {
    _id: testsIds.alpt,
    abbreviation: "ALPT",
    name: "Arabic Language Proficiency Test",
    languages: [languagesIds.arabic],
    url: "https://www.arabacademy.com/alpt",
  },
  {
    _id: testsIds.hsk,
    abbreviation: "HSK",
    name: "Hanyu Shuiping Kaoshi",
    languages: [languagesIds.chinese],
    url: "http://www.chinesetest.cn/index.do",
  },
  {
    _id: testsIds.tocfl,
    abbreviation: "TOCFL",
    name: "Test of Chinese as a Foreign Language",
    languages: [languagesIds.chinese],
    url: "https://tocfl.edu.tw/",
  },
  {
    _id: testsIds.ilce,
    abbreviation: "ILCE",
    name: "International Language Certifications Exams",
    languages: [
      languagesIds.chinese,
      languagesIds.english,
      languagesIds.italian,
      languagesIds.japanese,
      languagesIds.german,
      languagesIds.russian,
      languagesIds.spanish,
      languagesIds.french,
      languagesIds.korean,
    ],
    url: "http://ilcecefrlanguageexams.com/",
  },
  {
    _id: testsIds.ecl,
    abbreviation: "ECL",
    name: "European Consortium for the Certificate of Attainment in Modern Languages",
    languages: [
      languagesIds.czech,
      languagesIds.english,
      languagesIds.french,
      languagesIds.german,
      languagesIds.hebrew,
      languagesIds.italian,
      languagesIds.russian,
      languagesIds.spanish,
    ],
    url: "https://eclexam.eu/languages/",
  },
  {
    _id: testsIds.cce,
    abbreviation: "CCE",
    name: "Czech Language Certificate Exam",
    languages: [languagesIds.czech],
    url: "https://ujop.cuni.cz/zkouska/certifikovana-zkouska-z-cestiny-pro-cizince-cce",
  },
  {
    _id: testsIds.staatsexamen_nt2,
    abbreviation: "Staatsexamen NT2",
    name: "Staatsexamen Nederlands als tweede taal",
    languages: [languagesIds.dutch],
    url: "https://www.staatsexamensnt2.nl/",
  },
  {
    _id: testsIds.cnavt,
    abbreviation: "CNaVT",
    name: "Certificaat Nederlands als Vreemde Taal",
    languages: [languagesIds.dutch],
    url: "https://cnavt.org/",
  },
  {
    _id: testsIds.cal,
    abbreviation: "CAL",
    name: "English Proficiency Tests",
    languages: [languagesIds.english],
    url: "https://www.cal.org/resource-center/publications-products/cal-ept",
  },
  {
    _id: testsIds.ielts,
    abbreviation: "IELTS",
    name: "International English Language Testing System",
    languages: [languagesIds.english],
    url: "https://www.ielts.org/",
  },
  {
    _id: testsIds.toefl,
    abbreviation: "TOEFL",
    name: "Test of English as a Foreign Language",
    languages: [languagesIds.english],
    url: "https://www.ets.org/toefl/",
  },
  {
    _id: testsIds.delf,
    abbreviation: "DELF",
    name: "Diplôme d'études en langue française",
    languages: [languagesIds.french],
    url: "http://www.delfdalf.fr/index-en.html",
  },
  {
    _id: testsIds.dalf,
    abbreviation: "DALF",
    name: "Diplôme approfondi de langue française",
    languages: [languagesIds.french],
    url: "http://www.delfdalf.fr/index-en.html",
  },
  {
    _id: testsIds.goethe,
    abbreviation: "",
    name: "Goethe Zertifikat Deutsch",
    languages: [languagesIds.german],
    url: "https://www.goethe.de/de/spr/kup/prf/prf.html",
  },
  {
    _id: testsIds.testdaf,
    abbreviation: "TestDaF",
    name: "Test Deutsch als Fremdsprache",
    languages: [languagesIds.german],
    url: "https://www.goethe.de/de/spr/kup/prf/prf/testdaf.html",
  },
  {
    _id: testsIds.telc,
    abbreviation: "TELC",
    name: "The European Language Certificates",
    languages: [
      languagesIds.german,
      languagesIds.italian,
      languagesIds.english,
      languagesIds.spanish,
      languagesIds.french,
      languagesIds.portuguese,
      languagesIds.russian,
      languagesIds.arabic,
      languagesIds.polish,
    ],
    url: "https://www.telc.net/",
  },
  {
    _id: testsIds.yael,
    abbreviation: "YAEL",
    name: "Hebrew Proficiency Test",
    languages: [languagesIds.hebrew],
    url: "https://nite.org.il/other-tests/yael/?lang=en",
  },
  {
    _id: testsIds.cils,
    abbreviation: "CILS",
    name: "Certificazione di Italiano come Lingua Straniera",
    languages: [languagesIds.italian],
    url: "https://cils.unistrasi.it/home.asp",
  },
  {
    _id: testsIds.celi,
    abbreviation: "CELI",
    name: "Certificato di Conoscenza della Lingua Italiana",
    languages: [languagesIds.italian],
    url: "http://www.cvcl.it/categorie/categoria-14",
  },
  {
    _id: testsIds.jlpt,
    abbreviation: "JLPT",
    name: "Japanese-Language Proficiency Test",
    languages: [languagesIds.japanese],
    url: "http://www.jlpt.jp/e/about/purpose.html",
  },
  {
    _id: testsIds.topik,
    abbreviation: "TOPIK",
    name: "Test of Proficiency in Korean",
    languages: [languagesIds.korean],
    url: "https://www.topik.go.kr/intro_index2.html",
  },
  {
    _id: testsIds.klat,
    abbreviation: "KLAT",
    name: "Korean Language Ability Test",
    languages: [languagesIds.korean],
    url: "http://www.kets.or.kr/",
  },
  {
    _id: testsIds.caple,
    abbreviation: "CAPLE",
    name: "Centro de Avaliação de Português Língua Estrangeira",
    languages: [languagesIds.portuguese],
    url: "https://caple.letras.ulisboa.pt/",
  },
  {
    _id: testsIds.dele,
    abbreviation: "DELE",
    name: "Diplomas de Español como Lengua Extranjera",
    languages: [languagesIds.spanish],
    url: "https://examenes.cervantes.es/es/dele/calificaciones",
  },
  {
    _id: testsIds.tisus,
    abbreviation: "TISUS",
    name: "Test i svenska för universitets- och högskolestudier",
    languages: [languagesIds.swedish],
    url: "https://www.su.se/svefler/tisus",
  },
  {
    _id: testsIds.swedex,
    abbreviation: "Swedex",
    name: "Swedish Examination",
    languages: [languagesIds.swedish],
    url: "https://www.folkuniversitetet.se/in-english/swedex-swedish-examinations/",
  },
  {
    _id: testsIds.torfl,
    abbreviation: "TORFL",
    name: "Test of Russian as a Foreign Language",
    languages: [languagesIds.russian],
    url: "https://english.spbu.ru/torfl",
  },
]);

db.languages.insertMany([
  {
    _id: languagesIds.arabic,
    i18n: "arabic",
    code: "ar",
    tests: [testsIds.alpt, testsIds.telc],
  },
  {
    _id: languagesIds.chinese,
    i18n: "chinese",
    code: "zh",
    tests: [testsIds.hsk, testsIds.tocfl, testsIds.ilce],
  },
  {
    _id: languagesIds.czech,
    i18n: "czech",
    code: "cs",
    tests: [testsIds.ecl, testsIds.cce],
  },
  {
    _id: languagesIds.dutch,
    i18n: "dutch",
    code: "nl",
    tests: [testsIds.staatsexamen_nt2, testsIds.cnavt],
  },
  {
    _id: languagesIds.english,
    i18n: "english",
    code: "en",
    tests: [
      testsIds.ecl,
      testsIds.ilce,
      testsIds.cal,
      testsIds.ielts,
      testsIds.telc,
    ],
  },
  {
    _id: languagesIds.french,
    i18n: "french",
    code: "fr",
    tests: [
      testsIds.ecl,
      testsIds.ilce,
      testsIds.delf,
      testsIds.dalf,
      testsIds.telc,
    ],
  },
  {
    _id: languagesIds.german,
    i18n: "german",
    code: "de",
    tests: [testsIds.ecl, testsIds.ilce, testsIds.telc, testsIds.testdaf],
  },
  {
    _id: languagesIds.hebrew,
    i18n: "hebrew",
    code: "he",
    tests: [testsIds.ecl, testsIds.yael],
  },
  {
    _id: languagesIds.italian,
    i18n: "italian",
    code: "it",
    tests: [
      testsIds.ecl,
      testsIds.ilce,
      testsIds.telc,
      testsIds.cils,
      testsIds.celi,
    ],
  },
  {
    _id: languagesIds.japanese,
    i18n: "japanese",
    code: "ja",
    tests: [testsIds.ilce, testsIds.jlpt],
  },
  {
    _id: languagesIds.korean,
    i18n: "korean",
    code: "ko",
    tests: [testsIds.ilce, testsIds.topik, testsIds.klat],
  },
  {
    _id: languagesIds.polish,
    i18n: "polish",
    code: "pl",
    tests: [testsIds.ecl, testsIds.telc],
  },
  {
    _id: languagesIds.portuguese,
    i18n: "portuguese",
    code: "pt",
    tests: [testsIds.telc, testsIds.caple],
  },
  {
    _id: languagesIds.russian,
    i18n: "russian",
    code: "ru",
    tests: [testsIds.ecl, testsIds.ilce, testsIds.telc, testsIds.torfl],
  },
  {
    _id: languagesIds.spanish,
    i18n: "spanish",
    code: "es",
    tests: [testsIds.ecl, testsIds.ilce, testsIds.telc, testsIds.dele],
  },
  {
    _id: languagesIds.swedish,
    i18n: "swedish",
    code: "sv",
    tests: [testsIds.swedex, testsIds.tisus],
  },
]);

db.levels.insertMany([
  { _id: levelsIds.a1, name: "A1" },
  { _id: levelsIds.a2, name: "A2" },
  { _id: levelsIds.b1, name: "B1" },
  { _id: levelsIds.b2, name: "B2" },
  { _id: levelsIds.c1, name: "C1" },
  { _id: levelsIds.c2, name: "C2" },
]);

print("END #################################################################");
